Repository Khaaz/AxonCore, pull requests merged in 2020-10, with the labels that each got.

#101 readme: update links into source
  README.md
Labels: hacktoberfest, semver: NA, t: docs

#102 feat: Add Reaction Collector
  src/Libraries/discordjs/DjsInterface.js
  src/Libraries/eris/ErisInterface.js
  src/Utility/Discord/Collectors/ReactionCollector.js
  types/Libraries/default.ts
  types/Libraries/definitions/types.ts
  types/Libraries/discordjs.ts
  types/Libraries/discordjs/types.ts
  types/Libraries/eris.ts
  types/Libraries/eris/types.ts
  types/Libraries/index.ts
  types/Utility/Discord/Collectors/ReactionCollector.ts
  types/index.ts
  types/misc/interfaces.ts
Labels: hacktoberfest, semver: minor, t: feature

#109 Fixing permissions in DM for bot owners
  src/AxonClient.js
  src/Core/Command/Command.js
  src/Core/Command/CommandPermissions.js
Labels: hacktoberfest, semver: patch, t: bugfix

#112 Returns the key's value from default language.
  src/Langs/TranslationManager.js
Labels: hacktoberfest, i: enhancement, semver: patch

#114 raw handler for Discord.js
  src/Libraries/discordjs/handlers/RawHandler.js
  src/Libraries/discordjs/handlers/index.js
Labels: hacktoberfest, i: libraries, semver: minor, t: feature
