Repository Khaaz/AxonCore, pull requests merged in 2020-02, with the labels that each got.

#53 fix(InMemoryProvider): saveGuild and saveAxon inconsistency.
  src/Database/InMemoryProvider.js
Labels: bug fix

#49 fix(InMemoryProvider): updateGuild and updateAxon return values
  src/Database/InMemoryProvider.js
  src/Database/JsonProvider.js
Labels: bug fix

#54 CI: Added Typescript checker
  .github/workflows/test.yaml
  package.json
Labels: ci, enhancement

#55 docs/typings(index.d.ts): Allow name of any group of AxonStaff
  index.d.ts
Labels: bug fix, typings

#57 fix/docs: Enum documentation fixes
  src/Libraries/discordjs/lib/DjsEnums.js
  src/Libraries/eris/lib/ErisEnums.js
  src/Utility/Constants/AxonEnums.js
  src/Utility/Constants/DiscordEnums.js
Labels: bug fix, documentation

#60 feat(Libraries/eris): InviteCreate + InviteDelete events
  src/Libraries/eris/handlers/InviteCreateHandler.js
  src/Libraries/eris/handlers/InviteDeleteHandler.js
  src/Libraries/eris/handlers/index.js
  src/Libraries/eris/lib/ErisEnums.js
Labels: eris, libraries

#63 feat(Libraries/djs): MessageReactionRemoveEmoji event
  src/Libraries/discordjs/handlers/MessageReactionRemoveEmojiHandler.js
  src/Libraries/discordjs/handlers/index.js
  src/Libraries/discordjs/lib/DjsEnums.js
Labels: djs, libraries
