Repository Khaaz/AxonCore, pull requests merged in 2020-07, with the labels that each got.

#91 Fix database memory leak/issue (Guild)
  src/Core/Models/GuildConfig.js
Labels: semver: patch, t: bugfix

#92 Fix AxonUtils.isBotStaff
  src/Utility/AxonUtils.js
Labels: semver: patch, t: bugfix, t: perf

#94 feat(CommandEnvironment): Add used label prop
  src/Core/Command/CommandEnvironment.js
  src/Core/CommandDispatcher.js
  types/Core/Command/CommandEnvironment.ts
Labels: i: enhancement, semver: minor, t: feature
